# Generated by Django 5.0 on 2023-12-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('usr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('usr_name', models.CharField(max_length=255)),
                ('usr_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
